package jp.co.casley.jankenapi.repository.db.dao.generate;

import java.util.List;
import jp.co.casley.jankenapi.repository.db.entity.generate.MtJankenComb;
import jp.co.casley.jankenapi.repository.db.entity.generate.MtJankenCombExample;
import jp.co.casley.jankenapi.repository.db.entity.generate.MtJankenCombKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MtJankenCombMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    long countByExample(MtJankenCombExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int deleteByExample(MtJankenCombExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int deleteByPrimaryKey(MtJankenCombKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int insert(MtJankenComb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int insertSelective(MtJankenComb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    List<MtJankenComb> selectByExampleWithRowbounds(MtJankenCombExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    List<MtJankenComb> selectByExample(MtJankenCombExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    MtJankenComb selectByPrimaryKey(MtJankenCombKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int updateByExampleSelective(@Param("record") MtJankenComb record, @Param("example") MtJankenCombExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int updateByExample(@Param("record") MtJankenComb record, @Param("example") MtJankenCombExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int updateByPrimaryKeySelective(MtJankenComb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.mt_janken_comb
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    int updateByPrimaryKey(MtJankenComb record);
}