package jp.co.casley.jankenapi.repository.db.entity.generate;

public class MtJankenCombKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.hand1
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String hand1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.hand2
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String hand2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.hand1
     *
     * @return the value of jankendb.mt_janken_comb.hand1
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getHand1() {
        return hand1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.hand1
     *
     * @param hand1 the value for jankendb.mt_janken_comb.hand1
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setHand1(String hand1) {
        this.hand1 = hand1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.hand2
     *
     * @return the value of jankendb.mt_janken_comb.hand2
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getHand2() {
        return hand2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.hand2
     *
     * @param hand2 the value for jankendb.mt_janken_comb.hand2
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setHand2(String hand2) {
        this.hand2 = hand2;
    }
}