package jp.co.casley.jankenapi.repository.db.entity.generate;

import java.util.Date;

public class MtJankenHand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String hand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.hand_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String handName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_hand.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String rowVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.hand
     *
     * @return the value of jankendb.mt_janken_hand.hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getHand() {
        return hand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.hand
     *
     * @param hand the value for jankendb.mt_janken_hand.hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setHand(String hand) {
        this.hand = hand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.hand_name
     *
     * @return the value of jankendb.mt_janken_hand.hand_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getHandName() {
        return handName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.hand_name
     *
     * @param handName the value for jankendb.mt_janken_hand.hand_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setHandName(String handName) {
        this.handName = handName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.create_date
     *
     * @return the value of jankendb.mt_janken_hand.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.create_date
     *
     * @param createDate the value for jankendb.mt_janken_hand.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.create_user
     *
     * @return the value of jankendb.mt_janken_hand.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.create_user
     *
     * @param createUser the value for jankendb.mt_janken_hand.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.update_date
     *
     * @return the value of jankendb.mt_janken_hand.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.update_date
     *
     * @param updateDate the value for jankendb.mt_janken_hand.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.update_user
     *
     * @return the value of jankendb.mt_janken_hand.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.update_user
     *
     * @param updateUser the value for jankendb.mt_janken_hand.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_hand.row_version
     *
     * @return the value of jankendb.mt_janken_hand.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_hand.row_version
     *
     * @param rowVersion the value for jankendb.mt_janken_hand.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setRowVersion(String rowVersion) {
        this.rowVersion = rowVersion;
    }
}