package jp.co.casley.jankenapi.repository.db.entity.generate;

import java.util.Date;

public class MtJankenComb extends MtJankenCombKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.result_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String resultName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.mt_janken_comb.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String rowVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.result
     *
     * @return the value of jankendb.mt_janken_comb.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.result
     *
     * @param result the value for jankendb.mt_janken_comb.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.result_name
     *
     * @return the value of jankendb.mt_janken_comb.result_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getResultName() {
        return resultName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.result_name
     *
     * @param resultName the value for jankendb.mt_janken_comb.result_name
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setResultName(String resultName) {
        this.resultName = resultName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.create_date
     *
     * @return the value of jankendb.mt_janken_comb.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.create_date
     *
     * @param createDate the value for jankendb.mt_janken_comb.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.create_user
     *
     * @return the value of jankendb.mt_janken_comb.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.create_user
     *
     * @param createUser the value for jankendb.mt_janken_comb.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.update_date
     *
     * @return the value of jankendb.mt_janken_comb.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.update_date
     *
     * @param updateDate the value for jankendb.mt_janken_comb.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.update_user
     *
     * @return the value of jankendb.mt_janken_comb.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.update_user
     *
     * @param updateUser the value for jankendb.mt_janken_comb.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.mt_janken_comb.row_version
     *
     * @return the value of jankendb.mt_janken_comb.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.mt_janken_comb.row_version
     *
     * @param rowVersion the value for jankendb.mt_janken_comb.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setRowVersion(String rowVersion) {
        this.rowVersion = rowVersion;
    }
}