package jp.co.casley.jankenapi.repository.db.entity.generate;

import java.util.Date;

public class TtJankenScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.score_no
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Integer scoreNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.client_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String clientHand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.server_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String serverHand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.user_id
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jankendb.tt_janken_score.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    private String rowVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.score_no
     *
     * @return the value of jankendb.tt_janken_score.score_no
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Integer getScoreNo() {
        return scoreNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.score_no
     *
     * @param scoreNo the value for jankendb.tt_janken_score.score_no
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setScoreNo(Integer scoreNo) {
        this.scoreNo = scoreNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.client_hand
     *
     * @return the value of jankendb.tt_janken_score.client_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getClientHand() {
        return clientHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.client_hand
     *
     * @param clientHand the value for jankendb.tt_janken_score.client_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setClientHand(String clientHand) {
        this.clientHand = clientHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.server_hand
     *
     * @return the value of jankendb.tt_janken_score.server_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getServerHand() {
        return serverHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.server_hand
     *
     * @param serverHand the value for jankendb.tt_janken_score.server_hand
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setServerHand(String serverHand) {
        this.serverHand = serverHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.result
     *
     * @return the value of jankendb.tt_janken_score.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.result
     *
     * @param result the value for jankendb.tt_janken_score.result
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.user_id
     *
     * @return the value of jankendb.tt_janken_score.user_id
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.user_id
     *
     * @param userId the value for jankendb.tt_janken_score.user_id
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.create_date
     *
     * @return the value of jankendb.tt_janken_score.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.create_date
     *
     * @param createDate the value for jankendb.tt_janken_score.create_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.create_user
     *
     * @return the value of jankendb.tt_janken_score.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.create_user
     *
     * @param createUser the value for jankendb.tt_janken_score.create_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.update_date
     *
     * @return the value of jankendb.tt_janken_score.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.update_date
     *
     * @param updateDate the value for jankendb.tt_janken_score.update_date
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.update_user
     *
     * @return the value of jankendb.tt_janken_score.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.update_user
     *
     * @param updateUser the value for jankendb.tt_janken_score.update_user
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jankendb.tt_janken_score.row_version
     *
     * @return the value of jankendb.tt_janken_score.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jankendb.tt_janken_score.row_version
     *
     * @param rowVersion the value for jankendb.tt_janken_score.row_version
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setRowVersion(String rowVersion) {
        this.rowVersion = rowVersion;
    }
}