package jp.co.casley.jankenapi.repository.db.entity.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TtJankenScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public TtJankenScoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScoreNoIsNull() {
            addCriterion("score_no is null");
            return (Criteria) this;
        }

        public Criteria andScoreNoIsNotNull() {
            addCriterion("score_no is not null");
            return (Criteria) this;
        }

        public Criteria andScoreNoEqualTo(Integer value) {
            addCriterion("score_no =", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoNotEqualTo(Integer value) {
            addCriterion("score_no <>", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoGreaterThan(Integer value) {
            addCriterion("score_no >", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("score_no >=", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoLessThan(Integer value) {
            addCriterion("score_no <", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoLessThanOrEqualTo(Integer value) {
            addCriterion("score_no <=", value, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoIn(List<Integer> values) {
            addCriterion("score_no in", values, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoNotIn(List<Integer> values) {
            addCriterion("score_no not in", values, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoBetween(Integer value1, Integer value2) {
            addCriterion("score_no between", value1, value2, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andScoreNoNotBetween(Integer value1, Integer value2) {
            addCriterion("score_no not between", value1, value2, "scoreNo");
            return (Criteria) this;
        }

        public Criteria andClientHandIsNull() {
            addCriterion("client_hand is null");
            return (Criteria) this;
        }

        public Criteria andClientHandIsNotNull() {
            addCriterion("client_hand is not null");
            return (Criteria) this;
        }

        public Criteria andClientHandEqualTo(String value) {
            addCriterion("client_hand =", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandNotEqualTo(String value) {
            addCriterion("client_hand <>", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandGreaterThan(String value) {
            addCriterion("client_hand >", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandGreaterThanOrEqualTo(String value) {
            addCriterion("client_hand >=", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandLessThan(String value) {
            addCriterion("client_hand <", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandLessThanOrEqualTo(String value) {
            addCriterion("client_hand <=", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandLike(String value) {
            addCriterion("client_hand like", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandNotLike(String value) {
            addCriterion("client_hand not like", value, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandIn(List<String> values) {
            addCriterion("client_hand in", values, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandNotIn(List<String> values) {
            addCriterion("client_hand not in", values, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandBetween(String value1, String value2) {
            addCriterion("client_hand between", value1, value2, "clientHand");
            return (Criteria) this;
        }

        public Criteria andClientHandNotBetween(String value1, String value2) {
            addCriterion("client_hand not between", value1, value2, "clientHand");
            return (Criteria) this;
        }

        public Criteria andServerHandIsNull() {
            addCriterion("server_hand is null");
            return (Criteria) this;
        }

        public Criteria andServerHandIsNotNull() {
            addCriterion("server_hand is not null");
            return (Criteria) this;
        }

        public Criteria andServerHandEqualTo(String value) {
            addCriterion("server_hand =", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandNotEqualTo(String value) {
            addCriterion("server_hand <>", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandGreaterThan(String value) {
            addCriterion("server_hand >", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandGreaterThanOrEqualTo(String value) {
            addCriterion("server_hand >=", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandLessThan(String value) {
            addCriterion("server_hand <", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandLessThanOrEqualTo(String value) {
            addCriterion("server_hand <=", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandLike(String value) {
            addCriterion("server_hand like", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandNotLike(String value) {
            addCriterion("server_hand not like", value, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandIn(List<String> values) {
            addCriterion("server_hand in", values, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandNotIn(List<String> values) {
            addCriterion("server_hand not in", values, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandBetween(String value1, String value2) {
            addCriterion("server_hand between", value1, value2, "serverHand");
            return (Criteria) this;
        }

        public Criteria andServerHandNotBetween(String value1, String value2) {
            addCriterion("server_hand not between", value1, value2, "serverHand");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("result like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("result not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("row_version is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("row_version is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(String value) {
            addCriterion("row_version =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(String value) {
            addCriterion("row_version <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(String value) {
            addCriterion("row_version >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(String value) {
            addCriterion("row_version >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(String value) {
            addCriterion("row_version <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(String value) {
            addCriterion("row_version <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLike(String value) {
            addCriterion("row_version like", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotLike(String value) {
            addCriterion("row_version not like", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<String> values) {
            addCriterion("row_version in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<String> values) {
            addCriterion("row_version not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(String value1, String value2) {
            addCriterion("row_version between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(String value1, String value2) {
            addCriterion("row_version not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 01 00:32:53 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jankendb.tt_janken_score
     *
     * @mbg.generated Fri Nov 01 00:32:53 JST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}